import type { POCExportPayload, POCGeneratorState } from "./types";

export function buildPOCExportPayload(
  state: POCGeneratorState,
  context: { generatedBy: string; sourceRoute: string; appVersion: string },
): POCExportPayload {
  return {
    metadata: {
      generatedAt: new Date().toISOString(),
      generatedBy: context.generatedBy,
      sourceRoute: context.sourceRoute,
      appVersion: context.appVersion,
    },
    configName: state.configName,
    config: state.config,
    implementationInstructions: [
      "Use the config payload as the source of truth for company branding, homepage widgets, and report setup.",
      "Wire the host app to build PortalApp inputs via buildPortalFromConfig(config).",
      "Implement Power BI embed token generation in backend and pass it through the portal adapter.",
      "Persist multi-view layouts and report selections by customer workspace policy.",
    ],
  };
}

export function buildPOCImplementationBrief(payload: POCExportPayload): string {
  const json = JSON.stringify(payload.config, null, 2);
  const instructions = payload.implementationInstructions.map((item, index) => `${index + 1}. ${item}`).join("\n");

  return `# POC Implementation Brief

## Metadata
- Generated at: ${payload.metadata.generatedAt}
- Generated by: ${payload.metadata.generatedBy}
- Source route: ${payload.metadata.sourceRoute}
- App version: ${payload.metadata.appVersion}
- POC name: ${payload.configName}

## Implementation Instructions
${instructions}

## Company POC Config
\`\`\`json
${json}
\`\`\`
`;
}

export function downloadTextFile(filename: string, content: string, contentType: string) {
  if (typeof window === "undefined") {
    return;
  }
  const blob = new Blob([content], { type: contentType });
  const url = window.URL.createObjectURL(blob);
  const link = window.document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  window.URL.revokeObjectURL(url);
}
